import Menu from '@/components/menu/Menu';
import { Sriracha } from 'next/font/google';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const sriracha = Sriracha({ weight: '400', subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={sriracha.className}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
